Repository entando/entando-process-driven-plugin, pull requests merged in 2020-06, with the labels that each got.

#132 everting changes on ProcessDefinition and fixing ProcessForm
  widgets/src/components/ProcessDefinition/ProcessDefinitionConfig.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionContainer.js
  widgets/src/components/ProcessDefinition/__tests__/ProcessDefinitionContainer.test.js
  widgets/src/components/ProcessDefinition/__tests__/__snapshots__/ProcessDefinitionContainer.test.js.snap
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/ProcessForm/ProcessFormContainer.js
  widgets/src/components/ProcessForm/__tests__/ProcessFormContainer.test.js
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormConfig.test.js.snap
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormContainer.test.js.snap
  widgets/src/mocks/app-builder/pages.js
Labels: approved, size/XL

#120 PDA-234: List process instances
  src/main/java/org/entando/plugins/pda/controller/AuthPermissions.java
  src/main/java/org/entando/plugins/pda/controller/process/ProcessInstanceController.java
  src/test/java/org/entando/plugins/pda/controller/process/ProcessInstanceControllerIntegrationTest.java
Labels: approved, size/L

#121 Pda 235 process list
  widgets/package.json
  widgets/src/App/App.js
  widgets/src/App/Menu.js
  widgets/src/api/__tests__/process.test.js
  widgets/src/api/pda/processes.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionContainer.js
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/ProcessList/ProcessListConfig.js
  widgets/src/components/ProcessList/ProcessListContainer.js
  widgets/src/components/ProcessList/__tests__/ProcessListContainer.test.js
  widgets/src/components/ProcessList/__tests__/__snapshots__/ProcessListContainer.test.js.snap
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/components/TaskDetails/__tests__/__snapshots__/TaskDetailsContainer.test.js.snap
  widgets/src/components/common/Table/InternalTableBody.js
  widgets/src/components/common/Table/__tests__/__snapshots__/InternalTableBody.test.js.snap
  widgets/src/custom-elements/ProcessListElement.js
  widgets/src/custom-elements/customEventsUtils.js
  widgets/src/index.js
  widgets/src/mocks/app-builder/pages.js
  widgets/src/mocks/app-builder/widgets.js
  widgets/src/mocks/pda/processList.js
Labels: approved, size/XL

#129 moving Process selection to config screen
  bundle/descriptor.yaml
  bundle/widgets/process-list-descriptor.yaml
  bundle/widgets/process-list.ftl
  widgets/src/App/App.css
  widgets/src/App/App.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionContainer.js
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/ProcessForm/ProcessFormContainer.js
  widgets/src/components/ProcessForm/__tests__/ProcessFormContainer.test.js
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormConfig.test.js.snap
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormContainer.test.js.snap
  widgets/src/components/ProcessList/ProcessListConfig.js
  widgets/src/components/ProcessList/ProcessListContainer.js
  widgets/src/components/ProcessList/__tests__/ProcessListContainer.test.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/custom-elements/GenericConfigElement.js
  widgets/src/custom-elements/ProcessListElement.js
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
  widgets/src/index.css
  widgets/src/index.js
  widgets/src/mocks/app-builder/pages.js
  widgets/src/utils.js
Labels: approved, size/XL

#133 PDA-234: Authenticated user as initiator
  src/main/java/org/entando/plugins/pda/controller/process/ProcessFormController.java
Labels: approved, size/XS

#134 fixing loader on ProcessForm component
  widgets/src/components/ProcessForm/ProcessFormContainer.js
Labels: approved, size/XS

#135 fixing table sorting
  widgets/src/api/pda/tasks.js
Labels: approved, size/XS

#136 Fix bundle
  buildBundle.sh
Labels: approved, size/XS

#137 ENDOC-34 Update README
  README.md
Labels: approved, size/XS
