Repository entando/entando-process-driven-plugin, pull requests merged in 2020-05, with the labels that each got.

#116 PDA-238 - Attachments' height to minHeight
  widgets/src/components/Attachments/AttachmentsContainer.js
Labels: size/XS

#117 removing patternfly dependencies from exported components
  widgets/src/components/Attachments/AttachmentsConfig.js
  widgets/src/components/OvertimeGraph/OvertimeGraphConfig.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionConfig.js
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/SummaryCard/SummaryCardConfig.js
  widgets/src/components/TaskComments/TaskCommentsConfig.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormConfig.js
  widgets/src/components/TaskDetails/TaskDetailsConfig.js
  widgets/src/components/TaskList/TaskListConfig.js
  widgets/src/components/common/WidgetConfig.js
Labels: size/M

#115 PDA-179 - multi schema support
  widgets/package-lock.json
  widgets/package.json
  widgets/src/components/Attachments/AttachmentsConfig.js
  widgets/src/components/OvertimeGraph/OvertimeGraphConfig.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionConfig.js
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormContainer.test.js.snap
  widgets/src/components/SummaryCard/SummaryCardConfig.js
  widgets/src/components/TaskComments/TaskCommentsConfig.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormConfig.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormConfig.test.js.snap
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/components/TaskDetails/TaskDetailsConfig.js
  widgets/src/components/TaskList/TaskListConfig.js
  widgets/src/components/common/form/JSONForm.js
  widgets/src/components/common/form/SchemaEditor/EditAddDialog.js
  widgets/src/components/common/form/SchemaEditor/JsonMultiFieldContainer.js
  widgets/src/components/common/form/SchemaEditor/SchemaContainer.js
  widgets/src/components/common/form/SchemaEditor/SchemaContainerControls.js
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
  widgets/src/mocks/app-builder/pages.js
Labels: size/XXL

#118 PDA-240 - multi schema in process form widget
  widgets/postman/Entando-PDA+CORE.postman_collection.json
  widgets/postman/Entando-PDA+CORE.postman_environment.json
  widgets/src/components/OvertimeGraph/__tests__/__snapshots__/OvertimeGraphConfig.test.js.snap
  widgets/src/components/ProcessDefinition/__tests__/__snapshots__/ProcessDefinitionConfig.test.js.snap
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/ProcessForm/ProcessFormContainer.js
  widgets/src/components/ProcessForm/__tests__/ProcessFormContainer.test.js
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormConfig.test.js.snap
  widgets/src/components/SummaryCard/__tests__/__snapshots__/SummaryCardConfig.test.js.snap
  widgets/src/components/TaskComments/__tests__/__snapshots__/TaskCommentsConfig.test.js.snap
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormConfig.test.js.snap
  widgets/src/components/TaskDetails/__tests__/__snapshots__/TaskDetailsConfig.test.js.snap
  widgets/src/components/TaskList/__tests__/__snapshots__/TaskListConfig.test.js.snap
  widgets/src/components/common/form/JSONForm.js
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
Labels: size/L

#119 PDA-241 add multi uischema process definition
  widgets/postman/Entando-PDA+CORE.postman_collection.json
  widgets/src/components/ProcessDefinition/ProcessDefinitionConfig.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionContainer.js
  widgets/src/components/ProcessDefinition/__tests__/__snapshots__/ProcessDefinitionConfig.test.js.snap
Labels: size/XL

#124 adding descriptors and ftl files for all widgets
  widgets/templates/overtime-graph-descriptor.yaml
  widgets/templates/overtime-graph.ftl
  widgets/templates/pda-connections-descriptor.yaml
  widgets/templates/pda-connections.ftl
  widgets/templates/process-definition-descriptor.yaml
  widgets/templates/process-definition.ftl
  widgets/templates/process-form-descriptor.yaml
  widgets/templates/process-form.ftl
  widgets/templates/summary-card-descriptor.yaml
  widgets/templates/summary-card.ftl
  widgets/templates/task-attachments-descriptor.yaml
  widgets/templates/task-attachments.ftl
  widgets/templates/task-comments-descriptor.yaml
  widgets/templates/task-comments.ftl
  widgets/templates/task-completion-form-descriptor.yaml
  widgets/templates/task-completion-form.ftl
Labels: approved, size/L

#125 moving folder structure and adding page models to the bundle
  bundle/page-models/pda-dashboard.ftl
  bundle/page-models/pda-dashboard.yaml
  bundle/page-models/pda-key-cloak.ftl
  bundle/page-models/pda-key-cloak.yaml
  bundle/page-models/pda-single-widget.ftl
  bundle/page-models/pda-single-widget.yaml
  bundle/page-models/pda-smart-inbox.ftl
  bundle/page-models/pda-smart-inbox.yaml
  bundle/page-models/pda-task-details.ftl
  bundle/page-models/pda-task-details.yaml
  bundle/widgets/overtime-graph-descriptor.yaml
  bundle/widgets/overtime-graph.ftl
  bundle/widgets/pda-connections-descriptor.yaml
  bundle/widgets/pda-connections.ftl
  bundle/widgets/process-definition-descriptor.yaml
  bundle/widgets/process-definition.ftl
  bundle/widgets/process-form-descriptor.yaml
  bundle/widgets/process-form.ftl
  bundle/widgets/summary-card-descriptor.yaml
  bundle/widgets/summary-card.ftl
  bundle/widgets/task-attachments-descriptor.yaml
  bundle/widgets/task-attachments.ftl
  bundle/widgets/task-comments-descriptor.yaml
  bundle/widgets/task-comments.ftl
  bundle/widgets/task-completion-form-descriptor.yaml
  bundle/widgets/task-completion-form.ftl
  bundle/widgets/task-details-descriptor.yaml
  bundle/widgets/task-details.ftl
  bundle/widgets/task-list-descriptor.yaml
  bundle/widgets/task-list.ftl
Labels: approved, size/XL

#127 add fragments to the bundle
  bundle/fragments/entando_keycloak_check.ftl
  bundle/fragments/entando_keycloak_check.yaml
  bundle/fragments/entando_pda_css_reset.ftl
  bundle/fragments/entando_pda_css_reset.yaml
  bundle/fragments/entando_pda_header.ftl
  bundle/fragments/entando_pda_header.yaml
  bundle/fragments/entando_pda_import_react.ftl
  bundle/fragments/entando_pda_import_react.yaml
  bundle/fragments/entando_pda_shared_css_js.ftl
  bundle/fragments/entando_pda_shared_css_js.yaml
  bundle/fragments/entando_pda_styles.ftl
  bundle/fragments/entando_pda_styles.yaml
Labels: approved, size/L

#128 fixing keycloak auth
  widgets/src/components/common/auth/withAuth.js
Labels: approved, size/S

#123 PDA-244: PDA bundle
  .gitignore
  buildBundle.sh
  bundle/descriptor.yaml
  bundle/fragments/entando_keycloak_check.ftl
  bundle/fragments/entando_keycloak_check.yaml
  bundle/fragments/entando_pda_css_reset.ftl
  bundle/fragments/entando_pda_css_reset.yaml
  bundle/fragments/entando_pda_header.ftl
  bundle/fragments/entando_pda_header.yaml
  bundle/fragments/entando_pda_import_react.ftl
  bundle/fragments/entando_pda_import_react.yaml
  bundle/fragments/entando_pda_shared_css_js.ftl
  bundle/fragments/entando_pda_shared_css_js.yaml
  bundle/fragments/entando_pda_styles.ftl
  bundle/fragments/entando_pda_styles.yaml
  bundle/package.json
  bundle/page-models/pda-dashboard.ftl
  bundle/page-models/pda-dashboard.yaml
  bundle/page-models/pda-keycloak.ftl
  bundle/page-models/pda-keycloak.yaml
  bundle/page-models/pda-single-widget.ftl
  bundle/page-models/pda-single-widget.yaml
  bundle/page-models/pda-smart-inbox.ftl
  bundle/page-models/pda-smart-inbox.yaml
  bundle/page-models/pda-task-details.ftl
  bundle/page-models/pda-task-details.yaml
  bundle/plugins/pda-plugin.yaml
  bundle/widgets/overtime-graph-descriptor.yaml
  bundle/widgets/overtime-graph.ftl
  bundle/widgets/pda-connections-descriptor.yaml
  bundle/widgets/pda-connections.ftl
  bundle/widgets/process-definition-descriptor.yaml
  bundle/widgets/process-definition.ftl
  bundle/widgets/process-form-descriptor.yaml
  bundle/widgets/process-form.ftl
  bundle/widgets/summary-card-descriptor.yaml
  bundle/widgets/summary-card.ftl
  bundle/widgets/task-attachments-descriptor.yaml
  bundle/widgets/task-attachments.ftl
  bundle/widgets/task-comments-descriptor.yaml
  bundle/widgets/task-comments.ftl
  bundle/widgets/task-completion-form-descriptor.yaml
  bundle/widgets/task-completion-form.ftl
  bundle/widgets/task-details-descriptor.yaml
  bundle/widgets/task-details.ftl
  bundle/widgets/task-list-descriptor.yaml
  bundle/widgets/task-list.ftl
  widgets/.env.production
  widgets/src/components/common/auth/withAuth.js
Labels: do-not-merge/work-in-progress, size/XXL

#122 adding new labels for SummaryCard
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
Labels: approved, size/M

#130 Update owners
  OWNERS
  OWNERS_ALIASES
Labels: size/XS

#131 Add labels to locales
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
Labels: size/S
