Repository entando/entando-process-driven-plugin, pull requests merged in 2020-03, with the labels that each got.

#91 PDA-163 Testing Jenkins X integration
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: size/M

#92 Updated Postman Collection
  Entando PDA Plugin.postman_collection.json
  src/main/java/org/entando/plugins/pda/controller/AuthPermissions.java
  src/main/java/org/entando/plugins/pda/controller/task/TaskAttachmentController.java
Labels: approved, size/M

#84 PDA-153 Implement task details navigation
  widgets/src/components/App/App.js
  widgets/src/components/OvertimeGraph/__tests__/__snapshots__/OvertimeGraphContainer.test.js.snap
  widgets/src/components/TaskDetails/Overview/OverviewHeader.js
  widgets/src/components/TaskDetails/Overview/OverviewNavigation.js
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
  widgets/src/components/TaskDetails/__tests__/TaskDetailsContainer.test.js
  widgets/src/components/TaskDetails/__tests__/__snapshots__/TaskDetailsContainer.test.js.snap
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/common/Table/InternalTableBody.js
  widgets/src/components/common/Table/Table.js
  widgets/src/custom-elements/TaskDetailsElement.js
  widgets/src/mocks/pda/taskList.api.js
Labels: size/L

#93 PDA-154 task list config fix (regression)
  widgets/src/components/TaskList/TaskListConfig.js
Labels: approved, size/M

#90 PDA-160 Keycloak Auth Listener
  Entando PDA Plugin.postman_collection.json
  README.md
  charts/entando-process-driven-apps/README.md
  charts/maven/README.md
  widgets/README.md
  widgets/src/components/OvertimeGraph/OvertimeGraphContainer.js
  widgets/src/components/OvertimeGraph/__tests__/OvertimeGraphConfig.test.js
  widgets/src/components/OvertimeGraph/__tests__/OvertimeGraphContainer.test.js
  widgets/src/components/OvertimeGraph/__tests__/__snapshots__/OvertimeGraphContainer.test.js.snap
  widgets/src/components/ProcessForm/ProcessFormContainer.js
  widgets/src/components/ProcessForm/__tests__/ProcessFormConfig.test.js
  widgets/src/components/ProcessForm/__tests__/ProcessFormContainer.test.js
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormContainer.test.js.snap
  widgets/src/components/SummaryCard/SummaryCardContainer.js
  widgets/src/components/SummaryCard/__tests__/SummaryCardConfig.test.js
  widgets/src/components/SummaryCard/__tests__/SummaryCardContainer.test.js
  widgets/src/components/SummaryCard/__tests__/__snapshots__/SummaryCardContainer.test.js.snap
  widgets/src/components/TaskComments/TaskCommentsContainer.js
  widgets/src/components/TaskComments/__tests__/TaskCommentsConfig.test.js
  widgets/src/components/TaskComments/__tests__/TaskCommentsContainer.test.js
  widgets/src/components/TaskComments/__tests__/__snapshots__/TaskCommentsContainer.test.js.snap
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskCompletionForm/__tests__/TaskCompletionFormConfig.test.js
  widgets/src/components/TaskCompletionForm/__tests__/TaskCompletionFormContainer.test.js
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
  widgets/src/components/TaskDetails/__tests__/TaskDetailsConfig.test.js
  widgets/src/components/TaskDetails/__tests__/TaskDetailsContainer.test.js
  widgets/src/components/TaskDetails/__tests__/__snapshots__/TaskDetailsContainer.test.js.snap
  widgets/src/components/TaskList/TaskListConfig.js
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/TaskList/__tests__/TaskListConfig.test.js
  widgets/src/components/TaskList/__tests__/TaskListContainer.test.js
  widgets/src/components/TaskList/__tests__/__snapshots__/TaskListContainer.test.js.snap
  widgets/src/components/UserAuth/index.js
  widgets/src/components/common/auth/Loader.js
  widgets/src/components/common/auth/MissingPermissions.js
  widgets/src/components/common/auth/withAuth.js
  widgets/src/custom-elements/UserAuthElement.js
  widgets/src/mocks/auth/keycloak.js
Labels: approved, size/XXL
