Repository entando/entando-process-driven-plugin, pull requests merged in 2020-04, with the labels that each got.

#63 PDA-105 Task List Widget Bulk Actions Checkboxes
  Entando PDA Plugin.postman_collection.json
  widgets/src/api/__tests__/attachments.test.js
  widgets/src/api/pda/tasks.js
  widgets/src/components/Attachments/__tests__/__snapshots__/AddAttachmentModal.test.js.snap
  widgets/src/components/Attachments/__tests__/__snapshots__/Attachment.test.js.snap
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/TaskList/__tests__/__snapshots__/TaskListContainer.test.js.snap
  widgets/src/components/TaskList/__tests__/normalizeData.test.js
  widgets/src/components/TaskList/normalizeData.js
  widgets/src/components/common/ConfirmDialog.js
  widgets/src/components/common/DropDownButton.js
  widgets/src/components/common/Table/InternalTableBody.js
  widgets/src/components/common/Table/InternalTableHeader.js
  widgets/src/components/common/Table/Table.js
  widgets/src/components/common/Table/TableBulkSelectContext.js
  widgets/src/components/common/Table/__tests__/__snapshots__/InternalTableBody.test.js.snap
  widgets/src/components/common/Table/__tests__/__snapshots__/Table.test.js.snap
  widgets/src/components/common/Table/custom/CheckboxCell.js
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
  widgets/src/mocks/pda/bulkActions.js
Labels: approved, size/XXL

#96 PDA-174 configured postman collection with automatic token refresh
  Entando PDA Plugin.postman_collection.json
Labels: approved, size/XXL

#97 PDA-168 Added tests and updated Postman Collection for Full Task Form Sample
  Entando PDA Plugin.postman_collection.json
  src/main/java/org/entando/plugins/pda/serializer/JsonSchemaFormSerializer.java
  src/test/java/org/entando/plugins/pda/controller/task/TaskFormControllerIntegrationTest.java
  src/test/java/org/entando/plugins/pda/serializer/JsonSchemaFormSerializerTest.java
  src/test/resources/full_task_form_json_schema.json
  src/test/resources/simple_task_form_json_schema.json
  src/test/resources/task_form_json_schema_1.json
  widgets/src/mocks/pda/diagram.svg
Labels: approved, size/L

#98 PDA-146 changed POST method
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/common/form/widgets/DateTimeWidget.js
  widgets/src/mocks/app-builder/widgets.js
Labels: size/M

#99 Pda 180
  widgets/src/api/makeRequest.js
  widgets/src/api/pda/attachments.js
  widgets/src/components/Attachments/Attachment.js
  widgets/src/components/Attachments/AttachmentsContainer.js
  widgets/src/components/Attachments/__tests__/Attachment.test.js
  widgets/src/components/Attachments/__tests__/__snapshots__/Attachment.test.js.snap
  widgets/src/components/Attachments/__tests__/__snapshots__/AttachmentsContainer.test.js.snap
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
Labels: size/L

#103 PDA-139 - updated updown widget
  widgets/src/components/common/form/JSONForm.js
  widgets/src/components/common/form/widgets/UpDownWidget.js
  widgets/src/mocks/app-builder/widgets.js
Labels: size/M

#102 PDA-193 - removed maxwidth from task details
  widgets/src/components/App/App.js
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
Labels: size/XS

#100 PDA-153 Handle change of rowsPerPage in TaskList
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/common/Table/Table.js
Labels: size/XS

#101 PDA-184 - bulk action disabled when no rows selected
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/common/DropDownButton.js
Labels: size/M

#104 PDA-182 - fixed widget box collapse/expand
  widgets/src/components/common/WidgetBox.js
Labels: size/XS

#105 fixing issues and making attachments work on Smart Inbox screen
  widgets/src/components/App/__tests__/__snapshots__/App.test.js.snap
  widgets/src/components/Attachments/AttachmentsContainer.js
  widgets/src/components/TaskComments/__tests__/__snapshots__/TaskCommentsContainer.test.js.snap
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/components/TaskDetails/Overview/OverviewHeader.js
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
  widgets/src/components/TaskDetails/__tests__/__snapshots__/TaskDetailsContainer.test.js.snap
  widgets/src/components/TaskList/__tests__/__snapshots__/TaskListContainer.test.js.snap
  widgets/src/mocks/app-builder/pages.js
Labels: approved, size/L

#108 PDA-201 - conditionally removed bottom margin
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
Labels: size/S

#106 PDA-146 - filter form data from inputData
  widgets/src/components/TaskComments/__tests__/__snapshots__/TaskCommentsContainer.test.js.snap
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/mocks/app-builder/widgets.js
Labels: size/M

#110 PDA 197 - Create ProcessDefinition widget
  widgets/package.json
  widgets/src/components/App/App.js
  widgets/src/components/App/Menu.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionConfig.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionContainer.js
  widgets/src/components/ProcessDefinition/__tests__/ProcessDefinitionConfig.test.js
  widgets/src/components/ProcessDefinition/__tests__/ProcessDefinitionContainer.test.js
  widgets/src/components/ProcessDefinition/__tests__/__snapshots__/ProcessDefinitionConfig.test.js.snap
  widgets/src/components/ProcessDefinition/__tests__/__snapshots__/ProcessDefinitionContainer.test.js.snap
  widgets/src/custom-elements/GenericConfigElement.js
  widgets/src/custom-elements/ProcessDefinitionElement.js
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
  widgets/src/index.js
  widgets/src/mocks/app-builder/pages.js
  widgets/src/mocks/app-builder/widgets.js
  widgets/src/theme.js
Labels: size/XL

#109 PDA-153 Fix resetting of page size on page change in TaskList
  widgets/src/components/TaskList/TaskListContainer.js
Labels: size/XS

#89 [PDA-122] updates to widgets
  Entando PDA Plugin.postman_collection.json
  src/test/resources/full_task_form_json_schema.json
  src/test/resources/simple_task_form_json_schema.json
  widgets/src/api/pda/tasks.js
  widgets/src/components/ProcessForm/__tests__/__snapshots__/ProcessFormContainer.test.js.snap
  widgets/src/components/TaskCompletionForm/__tests__/__snapshots__/TaskCompletionFormContainer.test.js.snap
  widgets/src/components/common/form/JSONForm.js
  widgets/src/components/common/form/templates/FieldTemplate.js
  widgets/src/components/common/form/templates/ObjectFieldTemplate.js
  widgets/src/components/common/form/uiSchemas/allFieldsForm.js
  widgets/src/mocks/taskCompletionForm/getFormSchema.js
Labels: size/XXL

#112 PDA-191 added POSTMAN collection + env variables
  widgets/postman/Entando-PDA+CORE.postman_collection.json
  widgets/postman/Entando-PDA+CORE.postman_environment.json
  widgets/postman/bootstrap-env.png
  widgets/postman/bootstrap-folder.png
  widgets/postman/bootstrap-requests.png
  widgets/postman/bootstrap-runner.png
  widgets/postman/readme.md
  widgets/src/mocks/app-builder/widgets.js
Labels: size/XXL

#113 PDA-183 attachments widget style update
  widgets/src/components/Attachments/AddAttachmentModal.js
  widgets/src/components/Attachments/Attachment.js
  widgets/src/components/Attachments/AttachmentsConfig.js
  widgets/src/components/Attachments/AttachmentsContainer.js
  widgets/src/components/Attachments/__tests__/__snapshots__/Attachment.test.js.snap
  widgets/src/components/Attachments/__tests__/__snapshots__/AttachmentsContainer.test.js.snap
  widgets/src/components/Connections/ConnectionsContainer.js
  widgets/src/components/OvertimeGraph/OvertimeGraphConfig.js
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/SummaryCard/SummaryCardConfig.js
  widgets/src/components/TaskComments/TaskCommentsConfig.js
  widgets/src/components/TaskComments/__tests__/__snapshots__/TaskCommentsContainer.test.js.snap
  widgets/src/components/TaskCompletionForm/TaskCompletionFormConfig.js
  widgets/src/components/TaskDetails/TaskDetailsConfig.js
  widgets/src/components/TaskList/TaskListConfig.js
Labels: size/L

#111 PDA-181 navigation fix
  widgets/postman/Entando-PDA+CORE.postman_collection.json
  widgets/src/App/App.css
  widgets/src/App/App.js
  widgets/src/App/Home.js
  widgets/src/App/Menu.js
  widgets/src/App/__tests__/App.test.js
  widgets/src/App/__tests__/Home.test.js
  widgets/src/App/__tests__/Menu.test.js
  widgets/src/App/__tests__/__snapshots__/App.test.js.snap
  widgets/src/App/__tests__/__snapshots__/Home.test.js.snap
  widgets/src/App/__tests__/__snapshots__/Menu.test.js.snap
  widgets/src/api/pda/tasks.js
  widgets/src/app/App.css
  widgets/src/app/App.js
  widgets/src/app/Home.js
  widgets/src/app/Menu.js
  widgets/src/app/__tests__/App.test.js
  widgets/src/app/__tests__/Home.test.js
  widgets/src/app/__tests__/Menu.test.js
  widgets/src/app/__tests__/__snapshots__/App.test.js.snap
  widgets/src/app/__tests__/__snapshots__/Home.test.js.snap
  widgets/src/app/__tests__/__snapshots__/Menu.test.js.snap
  widgets/src/components/App/App.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
  widgets/src/components/TaskDetails/__tests__/__snapshots__/TaskDetailsContainer.test.js.snap
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/TaskList/__tests__/__snapshots__/TaskListContainer.test.js.snap
  widgets/src/components/common/DropDownButton.js
  widgets/src/components/common/Table/InternalTableBody.js
  widgets/src/components/common/Table/InternalTableCell.js
  widgets/src/components/common/Table/Table.js
  widgets/src/components/common/Table/__tests__/__snapshots__/InternalTableBody.test.js.snap
  widgets/src/components/common/Table/__tests__/__snapshots__/Table.test.js.snap
  widgets/src/custom-elements/AttachmentsElement.js
  widgets/src/custom-elements/TaskCommentsElement.js
  widgets/src/custom-elements/TaskCompletionFormElement.js
  widgets/src/custom-elements/TaskDetailsElement.js
  widgets/src/custom-elements/TaskListElement.js
  widgets/src/custom-elements/customEventsUtils.js
  widgets/src/i18n/locales/en.json
  widgets/src/i18n/locales/it.json
  widgets/src/index.js
  widgets/src/mocks/app-builder/pages.js
  widgets/src/pages/index.css
  widgets/src/pages/main-content-layouts.css
  widgets/src/pages/smart-inbox/index.js
  widgets/src/pages/task-details/index.js
Labels: size/XXL

#114 PDA-192 added save settings wrapper for local dev
  widgets/src/App/App.js
  widgets/src/App/Menu.js
  widgets/src/api/__tests__/pages.test.js
  widgets/src/api/app-builder/pages.js
  widgets/src/app/App.css
  widgets/src/app/App.js
  widgets/src/app/Home.js
  widgets/src/app/Menu.js
  widgets/src/app/__tests__/App.test.js
  widgets/src/app/__tests__/Home.test.js
  widgets/src/app/__tests__/Menu.test.js
  widgets/src/app/__tests__/__snapshots__/App.test.js.snap
  widgets/src/app/__tests__/__snapshots__/Home.test.js.snap
  widgets/src/app/__tests__/__snapshots__/Menu.test.js.snap
  widgets/src/components/Attachments/AttachmentsConfig.js
  widgets/src/components/Attachments/AttachmentsContainer.js
  widgets/src/components/OvertimeGraph/OvertimeGraphConfig.js
  widgets/src/components/OvertimeGraph/OvertimeGraphContainer.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionConfig.js
  widgets/src/components/ProcessDefinition/ProcessDefinitionContainer.js
  widgets/src/components/ProcessForm/ProcessFormConfig.js
  widgets/src/components/ProcessForm/ProcessFormContainer.js
  widgets/src/components/SummaryCard/SummaryCardConfig.js
  widgets/src/components/SummaryCard/SummaryCardContainer.js
  widgets/src/components/TaskComments/AddComment.js
  widgets/src/components/TaskComments/TaskCommentsConfig.js
  widgets/src/components/TaskComments/TaskCommentsContainer.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormConfig.js
  widgets/src/components/TaskCompletionForm/TaskCompletionFormContainer.js
  widgets/src/components/TaskDetails/TaskDetailsConfig.js
  widgets/src/components/TaskDetails/TaskDetailsContainer.js
  widgets/src/components/TaskList/TaskListConfig.js
  widgets/src/components/TaskList/TaskListContainer.js
  widgets/src/components/common/WidgetConfig.js
  widgets/src/mocks/app-builder/pages.js
Labels: size/XXL
